AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Lambda Web Adapter Application

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  SampleApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["node", "dist/index.js"]
      Architectures:
        - x86_64
      Events:
        ApiGatewayEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootPath:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
    Metadata:
      DockerTag: nodejs22-v1
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt SampleApiFunction.Arn